%YAML:1.0
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/IMU_POSE_0"
image0_topic: "/tutorial/image"
output_path: "/home/elvis/catkin_ws/src/VINS-Fusion/output/"

cam0_calib: "cameracalibrate.yaml"
image_width: 960
image_height: 640


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.01020345, -0.99989755, -0.01003897, 0.00017181, 
         -0.02799242, -0.00974994, -0.99956058, -0.00000369, 
          -0.99955606, 0.01047998, -0.02789007, -0.00007589, 
          0.0, 0.0, 0.0, 1.0] 

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.105e-4         # accelerometer measurement noise standard deviation. #0.2   0.04 0.00002148069451
gyr_n: 2.858e-4        # gyroscope measurement noise standard deviation.     #0.05  0.004 0.00002917280101
acc_w: 2.15e-3        # accelerometer bias random work noise standard deviation.  #0.02 0.0002194019068 
gyr_w: 1.093e-3    # gyroscope bias random work noise standard deviation.     #4.0e-5  0.0001114744097
g_norm: 9.81         # gravity magnitude




#unsynchronization parameters
estimate_td: 0                     # online estimate time offset between camera and imu
td: -0.18212974748083613           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/elvis/catkin_ws/src/VINS-Fusion/output/" # save and load path
save_image: 0                  # save image in pose graph for visualization prupose; you can close this function by setting 0 
