%YAML:1.0
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/IMU_POSE_0"
image0_topic: "/tutorial/image"
output_path: "/home/jaron/catkin_ws/src/VINS-Fusion-gpu-cv4/output/"

cam0_calib: "cameracalibrate.yaml"
image_width: 960
image_height: 640


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -0.01768089,   -0.98968371,   0.14217432,  -0.02008951,
            0.07492099,   -0.14310819,  -0.98686721,  -0.09474725,
            0.99703271,   -0.00679685,   0.07667836,  -0.19385949,
            0.0       ,    0.0       ,   0.0       ,   1.0        ]
#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 60            # max feature number in feature tracking
min_dist: 10            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 3.01672e-2        # accelerometer measurement noise standard deviation. #0.2     2.1331e-4 
gyr_n: 3.83535e-2        # gyroscope measurement noise standard deviation.     #0.05  2.7119e-4 
acc_w: 1.68313e-3        # accelerometer bias random work noise standard deviation.  #0.02 2.3803e-3
gyr_w: 8.91308e-2        # gyroscope bias random work noise standard deviation.     #4.0e-5  1.2605e-3 
g_norm: 9.8         # gravity magnitude




#unsynchronization parameters
estimate_td: 1                     # online estimate time offset between camera and imu
td: 0.00           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/elvis/catkin_ws/src/VINS-Fusion/output/" # save and load path
save_image: 0                  # save image in pose graph for visualization prupose; you can close this function by setting 0 
